name: 'Goose Recipe Shortener'
description: 'Generate a Goose deep link from a recipe file and optionally shorten it.'
icon: link-2
color: black
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'github-action'
inputs:
  recipe_path:
    description: 'Path to the Goose recipe file.'
    required: true
  shortener:
    description: 'Shortener to use: shortio, custom'
    required: false
  short_url_path:
    description: 'The path for the shortened URL'
    required: false
  shortio_api_key:
    description: 'short.io API key.'
    required: false
  shortio_domain:
    description: 'short.io domain.'
    required: false
  custom_shortener_path:
    description: 'Path to custom JavaScript shortener file (when shortener is "custom")'
    required: false
outputs:
  goose_deep_link:
    description: 'The generated Goose deep link.'
  short_url:
    description: 'The shortened URL.' 
