steps:
  - label: ":goose: Generate Deep Link"
    plugins:
      - ./.buildkite/goose_recipe_shortener_git:
          recipe_path: tests/fixtures/example-recipe.yaml

  - label: ":goose: Verify Custom Shortener"
    plugins:
      - ./.buildkite/goose_recipe_shortener_git:
          recipe_path: tests/fixtures/example-recipe.yaml
          shortener: custom
          short_url_path: test-custom-shortener
          custom_shortener_path: examples/custom-shortener.js
