steps:
  - label: ":goose: Generate Deep Link"
    if: build.branch == "main"
    plugins:
      - https://github.com/aaalaniz/goose-recipe-shortener.git#main:
          recipe_path: tests/fixtures/example-recipe.yaml

  - label: ":goose: Verify Custom Shortener"
    if: build.branch == "main"
    plugins:
      - https://github.com/aaalaniz/goose-recipe-shortener.git#main:
          recipe_path: tests/fixtures/example-recipe.yaml
          shortener: custom
          short_url_path: test-custom-shortener
          custom_shortener_path: examples/custom-shortener.js
