name: Goose Recipe Shortener CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        recipe: [tests/fixtures/example-recipe.yaml, goose-session.yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Setup CI 
        uses: ./.github/actions/setup-goose-recipe-shortener-ci

      - name: Run unit tests
        run: npm test

      - name: Test action
        uses: ./
        with:
          recipe_path: ${{ matrix.recipe }}

  publish-recipe:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs: build-and-test 
    steps:
      - name: Setup CI 
        uses: ./.github/actions/setup-goose-recipe-shortener-ci

      - name: Publish Recipe
        uses: ./
        with:
          recipe_path: goose-session.yaml
          shortener: shortio
          short_url_path: goose-recipe-shortener 
          shortio_api_key: ${{ secrets.SHORTIO_API_KEY }}
          shortio_domain: ${{ secrets.SHORTIO_DOMAIN }}